// FICHIER GÉNÉRÉ par lockhaccp/scripts/pms/synchroniser_vitrine.ts — ne pas modifier.
// Questions du générateur de PMS, dans l'ordre du questionnaire (spec §6).
// Étape 1 = choix du métier (hors référentiel), étape 7 = récapitulatif.
import type { Condition, MetierId, Question } from "./types";

const TOUJOURS: Condition = { toujours: true };

const RESTAURATION: MetierId[] = ["restauration_commerciale", "traiteur", "restauration_collective"];

/** Métiers qui cuisinent à l'avance (refroidissement, remise en température). */
const CUISSON_AVANCE: MetierId[] = [
  ...RESTAURATION,
  "boulangerie_patisserie",
  "boucherie_charcuterie",
];

/** Métiers qui décongèlent ou congèlent eux-mêmes. */
const CONGELATION: MetierId[] = [
  ...RESTAURATION,
  "boulangerie_patisserie",
  "boucherie_charcuterie",
  "poissonnerie",
  "glacier_chocolatier",
];

export const QUESTIONS: Question[] = [
  // ─── Étape 2 : votre activité ───────────────────────────────────────────
  {
    id: "activite.jours_ouverture",
    etape: 2,
    texte: "Quels jours êtes-vous ouvert ?",
    type: "jours",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "activite.services_par_jour",
    etape: 2,
    texte: "Combien de services faites-vous par jour ?",
    aide: "1 si vous servez uniquement le midi ou le soir, 2 si vous servez le midi et le soir.",
    type: "nombre",
    metiers: RESTAURATION,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "activite.modes_vente",
    etape: 2,
    texte: "Comment vos clients reçoivent-ils vos produits ?",
    type: "choix_multiple",
    options: [
      { valeur: "sur_place", libelle: "Sur place" },
      { valeur: "emporter", libelle: "À emporter" },
      { valeur: "livraison", libelle: "Livraison" },
    ],
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "activite.volume_jour",
    etape: 2,
    texte: "Combien de couverts ou de clients servez-vous par jour, en moyenne ?",
    type: "nombre",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "activite.alcool",
    etape: 2,
    texte: "Servez-vous ou vendez-vous des boissons alcoolisées ?",
    type: "oui_non",
    metiers: ["restauration_commerciale", "traiteur", "epicerie_primeur", "cremerie_fromagerie"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "activite.publics",
    etape: 2,
    texte: "Quels publics servez-vous ?",
    type: "choix_multiple",
    options: [
      { valeur: "scolaire", libelle: "Scolaire" },
      { valeur: "petite_enfance", libelle: "Petite enfance" },
      { valeur: "sante", libelle: "Santé (hôpital, clinique)" },
      { valeur: "personnes_agees", libelle: "Personnes âgées (EHPAD, résidence)" },
      { valeur: "entreprise", libelle: "Entreprise ou administration" },
    ],
    metiers: ["restauration_collective"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "activite.livre_collectivites",
    etape: 2,
    texte: "Livrez-vous des collectivités (écoles, entreprises, établissements de santé) ?",
    type: "oui_non",
    metiers: ["traiteur"],
    condition: TOUJOURS,
    obligatoire: true,
  },

  // ─── Étape 3 : ce que vous préparez ─────────────────────────────────────
  {
    id: "prep.viande_bovine",
    etape: 3,
    texte: "Servez-vous ou vendez-vous de la viande bovine ?",
    aide: "Bœuf, veau, y compris dans des plats (burger, bolognaise, pot-au-feu…).",
    type: "oui_non",
    metiers: [...RESTAURATION, "boucherie_charcuterie"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.autres_viandes_crues",
    etape: 3,
    texte: "Achetez-vous du porc, de la volaille ou de l'agneau crus pour les cuisiner ?",
    type: "oui_non",
    metiers: RESTAURATION,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.produits_viande_achetes",
    etape: 3,
    texte: "Utilisez-vous des produits à base de viande achetés prêts ?",
    aide: "Saucisses, merguez, nuggets, cordons bleus, lasagnes, raviolis, jambon cuit…",
    type: "oui_non",
    metiers: RESTAURATION,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.viande_hachee",
    etape: 3,
    texte: "Préparez-vous vous-même de la viande hachée (steaks hachés, farces) ?",
    type: "oui_non",
    metiers: [...RESTAURATION, "boucherie_charcuterie"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.poisson_cru",
    etape: 3,
    texte: "Servez-vous ou vendez-vous du poisson cru ou peu cuit ?",
    aide: "Sushis, tartares, carpaccios, ceviches, poisson mariné.",
    type: "oui_non",
    metiers: ["restauration_commerciale", "traiteur", "poissonnerie"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.coquillages",
    etape: 3,
    texte: "Servez-vous ou vendez-vous des coquillages vivants ?",
    aide: "Huîtres, moules, palourdes, coques, praires…",
    type: "oui_non",
    metiers: ["restauration_commerciale", "traiteur", "poissonnerie"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.oeufs_crus",
    etape: 3,
    texte: "Préparez-vous des recettes à base d'œufs crus ?",
    aide: "Mayonnaise maison, mousse au chocolat, tiramisu, crème anglaise peu cuite…",
    type: "oui_non",
    metiers: [...RESTAURATION, "boulangerie_patisserie", "glacier_chocolatier"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.legumes_crus",
    etape: 3,
    texte: "Préparez-vous des fruits ou des légumes servis crus ?",
    aide: "Salades, crudités, garnitures de sandwichs, fruits frais découpés.",
    type: "oui_non",
    metiers: [...RESTAURATION, "boulangerie_patisserie"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.conserves",
    etape: 3,
    texte: "Ouvrez-vous des boîtes de conserve ?",
    type: "oui_non",
    metiers: RESTAURATION,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.cuisson_avance",
    etape: 3,
    texte: "Cuisinez-vous à l'avance des préparations que vous refroidissez pour plus tard ?",
    aide: "Sauces, fonds, crème pâtissière, plats cuisinés préparés la veille…",
    type: "oui_non",
    metiers: CUISSON_AVANCE,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.remise_temperature",
    etape: 3,
    texte: "Réchauffez-vous des préparations froides pour les servir chaudes ?",
    aide: "Vos propres préparations de la veille ou des plats achetés réfrigérés.",
    type: "oui_non",
    metiers: CUISSON_AVANCE,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.maintien_chaud",
    etape: 3,
    texte: "Gardez-vous des plats au chaud avant de les servir ou de les vendre ?",
    aide: "Bain-marie, vitrine chaude, rôtissoire, étuve.",
    type: "oui_non",
    metiers: CUISSON_AVANCE,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.decongelation",
    etape: 3,
    texte: "Décongelez-vous des produits ?",
    type: "oui_non",
    metiers: CONGELATION,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.congelation_maison",
    etape: 3,
    texte: "Congelez-vous vous-même des produits frais ou des préparations ?",
    type: "oui_non",
    metiers: CONGELATION,
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.fait_maison",
    etape: 3,
    texte: "Utilisez-vous la mention « fait maison » sur votre carte ?",
    type: "oui_non",
    metiers: ["restauration_commerciale", "traiteur"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.glaces_maison",
    etape: 3,
    texte: "Fabriquez-vous vos glaces à partir d'un mélange que vous pasteurisez vous-même ?",
    type: "oui_non",
    metiers: ["glacier_chocolatier"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.lait_cru",
    etape: 3,
    texte: "Vendez-vous des fromages ou des produits au lait cru ?",
    type: "oui_non",
    metiers: ["cremerie_fromagerie", "epicerie_primeur"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.cave_affinage",
    etape: 3,
    texte: "Affinez-vous des fromages en cave ?",
    type: "oui_non",
    metiers: ["cremerie_fromagerie"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.decoupe",
    etape: 3,
    texte: "Coupez-vous ou tranchez-vous des produits à la demande ?",
    aide: "Trancheuse à jambon, coupe de fromage, découpe de viande devant le client.",
    type: "oui_non",
    metiers: ["boucherie_charcuterie", "cremerie_fromagerie", "epicerie_primeur"],
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "prep.fruits_legumes_vrac",
    etape: 3,
    texte: "Vendez-vous des fruits et légumes frais en vrac ?",
    type: "oui_non",
    metiers: ["epicerie_primeur"],
    condition: TOUJOURS,
    obligatoire: true,
  },

  // ─── Étape 4 : vos équipements ──────────────────────────────────────────
  {
    id: "equipements.froids",
    etape: 4,
    texte: "Quels sont vos équipements froids ?",
    aide:
      "Ajoutez chaque réfrigérateur, congélateur, chambre froide ou vitrine, avec un nom qui " +
      "permet de le reconnaître (« Frigo viandes », « Vitrine desserts ») et sa température de " +
      "consigne (nous vous proposons la consigne réglementaire selon le type d'équipement). " +
      "Chacun aura sa ligne dans votre tableau HACCP et sa colonne dans votre registre.",
    type: "liste_equipements_froids",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "equipements.friteuses",
    etape: 4,
    texte: "Avez-vous une ou plusieurs friteuses ?",
    aide: "Donnez un nom à chacune (« Friteuse frites », « Friteuse beignets »).",
    type: "liste_friteuses",
    metiers: [...RESTAURATION, "boulangerie_patisserie"],
    condition: TOUJOURS,
    obligatoire: false,
  },
  {
    id: "equipements.cellule_refroidissement",
    etape: 4,
    texte: "Avez-vous une cellule de refroidissement rapide ?",
    type: "oui_non",
    metiers: CUISSON_AVANCE,
    condition: { question: "prep.cuisson_avance", egal: true },
    obligatoire: true,
  },

  // ─── Étape 5 : votre nettoyage ──────────────────────────────────────────
  {
    id: "nettoyage.zones",
    etape: 5,
    texte: "Quelles sont les zones de votre établissement et les surfaces à nettoyer ?",
    aide:
      "Nous vous proposons des zones habituelles pour votre métier : gardez celles qui existent " +
      "chez vous, renommez-les et indiquez la fréquence de nettoyage de chaque surface.",
    type: "liste_zones",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "nettoyage.produits",
    etape: 5,
    texte: "Quels produits d'entretien utilisez-vous ?",
    aide:
      "Pour chaque produit : son nom, son usage (dégraissant, désinfectant…), sa dilution " +
      "(« prêt à l'emploi » ou dose indiquée sur l'étiquette), son temps d'action et s'il faut rincer.",
    type: "liste_produits_entretien",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "nettoyage.prestataire_nuisibles",
    etape: 5,
    texte: "Avez-vous un contrat avec une entreprise de lutte contre les nuisibles ?",
    type: "oui_non",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },

  // ─── Étape 6 : votre personnel ──────────────────────────────────────────
  {
    id: "personnel.effectif",
    etape: 6,
    texte: "Combien de salariés avez-vous ?",
    aide: "Indiquez 0 si vous travaillez seul.",
    type: "nombre",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "personnel.formation_hygiene",
    etape: 6,
    texte: "Au moins une personne de l'établissement a-t-elle suivi une formation en hygiène alimentaire ?",
    type: "oui_non",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },

  // ─── Étape 8 : vos coordonnées ──────────────────────────────────────────
  {
    id: "coordonnees.nom",
    etape: 8,
    texte: "Nom de l'établissement",
    type: "texte",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "coordonnees.adresse",
    etape: 8,
    texte: "Adresse",
    type: "texte",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "coordonnees.code_postal",
    etape: 8,
    texte: "Code postal",
    type: "texte",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "coordonnees.ville",
    etape: 8,
    texte: "Ville",
    type: "texte",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "coordonnees.telephone",
    etape: 8,
    texte: "Téléphone",
    aide: "Il apparaîtra sur vos affiches et vos registres.",
    type: "texte",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "coordonnees.email",
    etape: 8,
    texte: "Adresse e-mail",
    aide: "Nous vous y envoyons votre PMS.",
    type: "texte",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
  {
    id: "coordonnees.consentement",
    etape: 8,
    texte: "J'accepte que LockHACCP me contacte par e-mail ou par téléphone au sujet de mon PMS et de l'application.",
    type: "oui_non",
    metiers: "tous",
    condition: TOUJOURS,
    obligatoire: true,
  },
];
